name: trivia_test_task
description: "Trivia test task"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  fluttertoast: ^8.2.12
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  html_unescape: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
